#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/buildpack-detect/help-functions"

# if there is no subcommand, show help
if [[ -z "$2" ]]; then
	cmd-buildpack-detect-help
	exit 0
else
	cmd-buildpack-detect-detect "$@"
fi
